### ISSUE TITLE
Creating a block then deleting it crashes Pyflow

### ISSUE THREAD

**Issue by AlexandreSajus** [Bycelium/PyFlow#235]
Try the following steps:
- launch Pyflow
- Press New...
- Create a block
- Delete it

The app crashes with error:
```
Traceback (most recent call last):
  File "C:\Users\asaju\Desktop\Bycelium\PyFlow\pyflow\blocks\widgets\blocktitle.py", line 85, in focusOutEvent
    self.readOnly = True
  File "C:\Users\asaju\Desktop\Bycelium\PyFlow\pyflow\blocks\widgets\blocktitle.py", line 63, in readOnly
    views = self.parent_block.scene().views()
AttributeError: 'NoneType' object has no attribute 'views'
[IPKernelApp] WARNING | Parent appears to have exited, shutting down.
```

**Comment by MathisFederico** [comment]
This was fixed in #232
