### ISSUE TITLE
PyFlow crashes because undefined symbol: _ZdlPvm

### ISSUE THREAD

**Issue by johnblommers** [Bycelium/PyFlow#299]
Installation goes normally and without error. But try to run PyFlow and there is a message about an undefined symbol `_ZdlPvm`. What might  the remedy be?

```bash
python3 -m pyflow
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/johnb/.local/lib/python3.9/site-packages/pyflow/__main__.py", line 22, in <module>
    from pyflow.graphics.window import Window
  File "/home/johnb/.local/lib/python3.9/site-packages/pyflow/graphics/window.py", line 22, in <module>
    from pyflow.graphics.widget import Widget
  File "/home/johnb/.local/lib/python3.9/site-packages/pyflow/graphics/widget.py", line 11, in <module>
    from pyflow.scene import Scene
  File "/home/johnb/.local/lib/python3.9/site-packages/pyflow/scene/__init__.py", line 6, in <module>
    from pyflow.scene.scene import Scene
  File "/home/johnb/.local/lib/python3.9/site-packages/pyflow/scene/scene.py", line 17, in <module>
    from pyflow.blocks.block import Block
  File "/home/johnb/.local/lib/python3.9/site-packages/pyflow/blocks/__init__.py", line 7, in <module>
    from pyflow.blocks.codeblock import CodeBlock
  File "/home/johnb/.local/lib/python3.9/site-packages/pyflow/blocks/codeblock.py", line 15, in <module>
    from pyflow.blocks.pyeditor import PythonEditor
  File "/home/johnb/.local/lib/python3.9/site-packages/pyflow/blocks/pyeditor.py", line 18, in <module>
    from PyQt5.Qsci import QsciScintilla, QsciLexerPython
ImportError: /home/johnb/.local/lib/python3.9/site-packages/PyQt5/Qsci.abi3.so: undefined symbol: _ZdlPvm, version Qt_5
```

System info:

```bash
qmake --version
QMake version 3.1
Using Qt version 5.15.2 in /usr/lib/x86_64-linux-gnu

python3 --version
Python 3.9.7

cat /etc/lsb-release
DISTRIB_ID=Pop
DISTRIB_RELEASE=21.10
DISTRIB_CODENAME=impish
DISTRIB_DESCRIPTION="Pop!_OS 21.10"

qtdiag
Qt 5.15.2 (x86_64-little_endian-lp64 shared (dynamic) release build; by GCC 11.2.0) on "xcb" 
OS: Pop!_OS 21.10 [linux version 5.16.11-76051611-generic]

Architecture: x86_64; features: SSE2 SSE3 SSSE3 SSE4.1 SSE4.2 AVX AVX2
<snip>
```

**Comment by johnblommers** [comment]
Update. I found the fix. Some dependencies are not installed on my system for whatever reason and they must be installed by hand:

```bash
sudo apt install python3-pyqt5-qsci  qutebrowser  qutebrowser-qtwebengine
```

Now PyFlow is working :-)

**Comment by MathisFederico** [comment]
Thanks for the clear issue & fix !
